#! /usr/bin/python2.7

import csv
import os
import unicodedata
import sys
import re
import time
from datetime import date
from datetime import datetime

print '!Type:CCard'

with open( sys.argv[1], 'rb') as csvfile:
	rows = csv.reader(csvfile, delimiter=',')
	for row in rows:
	  year, month, day = row[0].split('/')
	  trans_date = date(int(year), int(month), int(day))
	  payee = row[1].decode('shift-jis').encode('utf-8')
	  payee = unicodedata.normalize('NFKC', payee.decode('utf8'))
	  payee = re.sub("\s\s+", " ", payee)
	  amount = row[6]
	  comment = row[2] + ' ' + row[3] + ' ' + row[5]
	  if row[10] != "JPY":
	    comment = comment + ' ' + row[10]
	    comment = comment + ' ' + row[9]
	    comment = comment + ' ' + row[11]
	  if row[4]:
	    comment = comment + ' ' + row[4]
	    newmonth = int(month)+(int(row[4][1])-1)
	    if newmonth > 12:
		newmonth = newmonth - 12
		newyear = int(year)+1
		year = str(newyear)
	    month = str(newmonth)
	    trans_date = date(int(year), int(month), int(day))
	  comment = comment.decode('shift-jis').encode('utf-8')
	  comment = unicodedata.normalize('NFKC', comment.decode('utf8'))

	  amount = -int(amount)

	  print 'D' + trans_date.strftime('%Y/%m/%d')
	  print 'T' + str(amount)
	  print 'P' + payee.encode('UTF-8')
	  print 'M' + comment.encode('UTF-8')
	  print '^'

