#! /usr/bin/python2.7

# Converts a SMBC VISA CSV file to QIF
#
# Usage: smbc_visa_to_qif ${FILENAME} > out.qif

import csv
import os
import unicodedata
import sys
import re

print '!Type:CCard'

with open( sys.argv[1], 'rb') as csvfile:
	rows = csv.reader(csvfile, delimiter=',')
	for row in rows:
	  date = row[0]
	  payee = row[1].decode('shift-jis').encode('utf-8')
	  payee = unicodedata.normalize('NFKC', payee.decode('utf8'))
	  payee = re.sub("\s\s+", " ", payee)
	  amount = row[6]
	  comment = row[2] + ' ' + row[3] + ' ' + row[5]
	  if row[9]:
	    comment = comment + ' ' + row[9]
	  if row[10]:
	    comment = comment + ' ' + row[10]
	  if row[11]:
	    comment = comment + ' ' + row[11]
	  comment = comment.decode('shift-jis').encode('utf-8')
	  comment = unicodedata.normalize('NFKC', comment.decode('utf8'))

	  print 'D' + date
	  print 'T-' + amount
	  print 'P' + payee.encode('UTF-8')
	  print 'M' + comment.encode('UTF-8')
	  print '^'
	  print

