#! /usr/bin/python2.7
# -*- coding: utf8 -*-


# This script takes a CSV file manually downloaded from Sumitomo-Mitsui Bank
# Card web site (https://www.smbc-card.com), converts it to Unicode, and
# rearranges it into QIF format.
# Charges spread out over multiple months ("kai") are handled.
# Charges in foreign currency are noted and the exchange rate is calculated.

import csv
import os
import unicodedata
import sys
import re
import time
from datetime import date
from datetime import datetime

print '!Type:CCard'

with open( sys.argv[1], 'rb') as csvfile:
	rows = csv.reader(csvfile, delimiter=',')
	for row in rows:
	  year, month, day = row[0].split('/')
	  trans_date = date(int(year), int(month), int(day))
	  payee = row[1].decode('shift-jis').encode('utf-8')
	  payee = unicodedata.normalize('NFKC', payee.decode('utf8'))
	  payee = re.sub("\s\s+", " ", payee)
	  amount = row[6]
	  # if the charge is made by someone other than you, add it)
	  if row[2] != "ご本人":
	    comment = row[2] + ' '
	  comment = 'Period: ' + row[5]
	  if row[10] and row[10] != "JPY":
	    comment = comment + ' ' + row[10]
	    comment = comment + ' ' + row[11] + ' (' + row[9] + ')'
	  if row[4]:
	    comment = comment + ' (' + row[4] + ')'
	    newmonth = int(month)+(int(row[4][1])-1)
	    if newmonth > 12:
		newmonth = newmonth - 12
		newyear = int(year)+1
		year = str(newyear)
	    month = str(newmonth)
	    trans_date = date(int(year), int(month), int(day))
	  comment = comment.decode('shift-jis').encode('utf-8')
	  comment = unicodedata.normalize('NFKC', comment.decode('utf8'))
	  comment = re.sub("\s\s+", " ", comment)

	  amount = -int(amount)

	  print 'D' + trans_date.strftime('%Y/%m/%d')
	  print 'T' + str(amount)
	  print 'P' + payee.encode('UTF-8')
	  print 'M' + comment.encode('UTF-8')
	  print '^'

