#! /usr/bin/env python2.7

import os
import sys
import unicodedata
import fileinput

for line in sys.stdin:
	line = line.rstrip('\n')
	line = line.decode('shift-jis').encode('utf-8')
	outline = unicodedata.normalize('NFKC', line.decode('utf8'))
	print (outline.encode('UTF-8'))
